---
name: on_polling_event
pack: op-st2-integration
description: Rule firing on op-st2-integration.polling_event.
enabled: true
trigger:
    type: op-st2-integration.polling_event
action:
    ref: op-st2-integration.output
    parameters:
        output: "{{trigger.firstName}} is a {{trigger.status}} User. Send email to {{trigger.email}}"