---
name: on_polling_event
pack: op_st2_integration
description: Rule firing on op-st2-integration.polling_event.
enabled: true
trigger:
    type: op_st2_integration.polling_event
action:
    ref: op_st2_integration.output
    parameters:
        output: "{{trigger.firstName}} is a {{trigger.status}} User. Send email to {{trigger.email}}"